# -*- coding: utf-8 -*-
"""testing and deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3AR2NcvwMfDmP1mYPuMY4NnJ9P5NcwV
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
data=pd.read_csv("heart.csv")
data.head()
data.columns
data.isnull().sum()
data.dtypes
df=data.drop(columns=['thalach','slope','thal'])
x=df.drop(columns=['target'])
y=df['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_val=accuracy_score(y_test,y_pred)
accuracy_val

